version: '3.8'

services:
  app:
    image: 'jc21/nginx-proxy-manager:2.10.3'
    container_name: 'nginx-proxy-manager'
    ports:
      - '80:80' # HTTP Port
      - '81:81' # Nginx Proxy Manager Web Admin
      - '443:443' # HTTS Port
    volumes:
      - $(pwd)/npm_data:/data
      - $(pwd)/letsencrypt:/etc/letsencrypt
    environment:
      - PUID=1024
      - PGID=1024
      - DISABLE_IPV6=true
      - DB_SQLITE_FILE=/data/database.sqlite
      - X_FRAME_OPTIONS=sameorigin
    networks:
      - nginx-proxymng-net
    healthcheck:
      test: [ 'CMD', '/bin/check-health' ]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 10s

    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s 
        max_attempts: 3
        window: 30s 

networks:
  nginx-proxymng-net:
    name: nginx-proxymng-net
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/28'
